-- Auto-generated by convert_schematic.py
-- Source: abyss_bridge.litematic
-- Blocks: 36
-- Load in pocket_client.lua with [S] → [Load from file…]
--
-- Coordinates: rx=right, ry=up, rz=forward (turtle facing north = +rz)

return {
  name   = "abyss_bridge",
  blocks = {
    {rx=    1, ry=    0, rz=    0, block="minecraft:copper_block"},
    {rx=    5, ry=    0, rz=    0, block="minecraft:copper_block"},
    {rx=    1, ry=    0, rz=    1, block="minecraft:copper_block"},
    {rx=    5, ry=    0, rz=    1, block="minecraft:copper_block"},
    {rx=    0, ry=    1, rz=    0, block="minecraft:copper_block"},
    {rx=    2, ry=    1, rz=    0, block="mekanism:block_steel"},
    {rx=    3, ry=    1, rz=    0, block="immersiveengineering:sheetmetal_steel"},
    {rx=    4, ry=    1, rz=    0, block="mekanism:block_steel"},
    {rx=    6, ry=    1, rz=    0, block="minecraft:copper_block"},
    {rx=    0, ry=    1, rz=    1, block="minecraft:copper_block"},
    {rx=    2, ry=    1, rz=    1, block="mekanism:block_steel"},
    {rx=    3, ry=    1, rz=    1, block="immersiveengineering:sheetmetal_steel"},
    {rx=    4, ry=    1, rz=    1, block="mekanism:block_steel"},
    {rx=    6, ry=    1, rz=    1, block="minecraft:copper_block"},
    {rx=    0, ry=    2, rz=    0, block="immersiveengineering:sheetmetal_steel"},
    {rx=    2, ry=    2, rz=    0, block="immersiveengineering:steel_fence"},
    {rx=    4, ry=    2, rz=    0, block="immersiveengineering:steel_fence"},
    {rx=    6, ry=    2, rz=    0, block="immersiveengineering:sheetmetal_steel"},
    {rx=    0, ry=    2, rz=    1, block="immersiveengineering:sheetmetal_steel"},
    {rx=    2, ry=    2, rz=    1, block="immersiveengineering:steel_fence"},
    {rx=    4, ry=    2, rz=    1, block="immersiveengineering:steel_fence"},
    {rx=    6, ry=    2, rz=    1, block="immersiveengineering:sheetmetal_steel"},
    {rx=    0, ry=    3, rz=    0, block="ae2:quartz_glass"},
    {rx=    6, ry=    3, rz=    0, block="ae2:quartz_glass"},
    {rx=    0, ry=    3, rz=    1, block="ae2:quartz_glass"},
    {rx=    6, ry=    3, rz=    1, block="ae2:quartz_glass"},
    {rx=    0, ry=    4, rz=    0, block="ae2:quartz_glass"},
    {rx=    6, ry=    4, rz=    0, block="ae2:quartz_glass"},
    {rx=    0, ry=    4, rz=    1, block="ae2:quartz_glass"},
    {rx=    6, ry=    4, rz=    1, block="ae2:quartz_glass"},
    {rx=    1, ry=    5, rz=    0, block="minecraft:copper_block"},
    {rx=    5, ry=    5, rz=    0, block="minecraft:copper_block"},
    {rx=    1, ry=    5, rz=    1, block="minecraft:copper_block"},
    {rx=    5, ry=    5, rz=    1, block="minecraft:copper_block"},
    {rx=    3, ry=    6, rz=    0, block="minecraft:copper_block"},
    {rx=    3, ry=    6, rz=    1, block="minecraft:copper_block"},
  },
}
